-- INSERT INTO comments
--     (username, comment)
-- VALUES
--     ('ilovemapsandnews','What an amazing article I really enjoyed listening to it'),
--     ('ilovethiswebsite','amazing'),
--     ('fire','i agree'),
--     ('whatshappening??','yes'),
--     ('ihopethiscommentworks','please');

-- INSERT INTO articles
--     (headline, a_date, author)
-- VALUES
--     ("Headline Test 1","2021-09-01","Myung Test"),
--     ("Headline Test 2","2022-10-01","Jeno Test"),
--     ("Headline Test 3","2016-05-21","Lomon Test");